ft-interactive/ge15

templates/sankey-index.html
updated styling to buttons and added glow to sankey labels
=> added glow to text labels and changed button styling

templates/sankey-index.html
fixed text shadow problem on iphone
=> Iphone label fix

client/js/data-table/forecast-summary.js, package.json
Fixed problem with not getting the correct dependencies: added 'koa-request' to package json (also got rid of a console.log in the client code)
=> added 'koa-request' to package json

client/js/coalition-forecast.main.js, server/routers/coalitionforecast/index.js, server/routers/data/coalition-data.js, server/routers/data/index.js, server/routers/index.js, templates/coalition-forecast.html
this PR adds a route for coalition probability data and a basic HTML scaffold for same
=> Coalition probability data

client/js/data/party-data.js, client/js/group-forecast-slopes.main.js, client/js/table/projections-decorator.js, client/scss/components/_results-table.scss, client/scss/graphics/_party-elements.scss, client/scss/graphics/_slope.scss, client/scss/pages/projections.scss, server/routers/data/coalition-data.js, server/routers/data/index.js, server/routers/data/slope-data.js, server/routers/projections/index.js, server/util/filters.js, templates/projections-index.html, templates/result-table.html
+ reordering constituencies
+ creating central party css file (nothing else is using this yet...)
=> adding national overview

templates/projections-index.html
shortened and cleaned up the first version of the introduction text.
=> Tweak copy on projections page

client/js/sankey.main.js
factor out bespoke party stuff in favour of the 'uk-political-parties' module
=> fix 'undefined' Ukip

client/scss/components/_article.scss, client/scss/components/_battle-nav.scss, server/routers/data/index.js, server/routers/data/slope-data.js, server/routers/projections/index.js, server/util/request-cache.js, templates/projections-index.html
=> Use Bertha to get group and their descriptions

templates/projections-index.html
... because it most likely won't be a formal coalition
=> Added "or alliances" to the coalitions header

templates/projections-widget.html
=> projections widget is truly standalone

templates/coalition-table.html
it was just one place after all
=> fix arithmetic

templates/sankey-index.html
Added a paragraph explaining why the totals are different from our headline figure.
=> Sankey copy change

client/js/coalition-calculator.main.js, client/scss/pages/coalition-calculator.scss, server/routers/coalitioncalculator/index.js, server/routers/index.js, templates/article.html, templates/coalition-calculator.html, templates/coalition-slider-handle.svg
Needs some work on the text still.
Steve to advise on layout once that's done.
=> creating coalition calculator page

client/js/coalition-calculator.main.js
=> Added Lab/SNP/Gr/SDLP/PC

server/service/result-national-overview.js, templates/projections-index.html, templates/result-national-overview.html
make the national overview use live data from Loki
=> Results service data

server/service/result-national-overview.js
or the chaching wont work as we want it to  (ie expires is never defined)
=> adding expires!

client/js/results.main.js, client/js/results/local-result-load.js, client/js/results/slopes.js, client/scss/components/_result-local-search-result.scss, client/scss/pages/results-index.scss, templates/result-national-coalitions.html, templates/results-index.html
local results  stuff
the neighbourhood stuff isn't wired up
all the styles are in _result-local-search-result.scss
=> Results local

client/scss/pages/ftcom.scss, server/routers/live-figures/index.js, templates/ftcom-embed-code.html, templates/ftcom-mockup.html, templates/liveblog-embed-code.html, templates/liveblog-mockup.html, templates/state-of-play.html
Plus env vars for setting where the homepage state-of-play links to.
And corrected state-of-play to show time in BST.
=> Endpoints for the two embed code snippets

client/scss/components/_result-local-search-result.scss, client/scss/components/_result-national-usefulLinks.scss, client/scss/pages/results-index.scss, templates/result-national-usefulLinks.html, templates/results-index.html
=> added top stories and link to in depth

client/scss/components/_result-national-usefulLinks.scss, templates/result-national-usefulLinks.html
fixed typo which prevented class from working
=> Fix top stories style

templates/result-national-usefulLinks.html
=> fix links on results page
